### PR TITLE
Implement return values as futures::sync::oneshot Futures

### PR DESCRIPTION
**Pull request by mrobakowski**
I implemented handling return values as futures using [futures::sync::oneshot](http://alexcrichton.com/futures-rs/futures/sync/oneshot/index.html). I am not sure if I handle all the generic stuff properly and wrote no tests besides modifing the existing `/testderive`.

### CODE REVIEW

**Comment by mrobakowski** [comment]
I also added `.idea` to `.gitignore` and removed the exisiting `.idea` folder.

**Comment by insanitybit** [comment]
This is awesome, and I'm super excited to have someone writing code for this library. Unfortunately this is a little off in terms of the feature. Let me state the goal of the feature.

Actor A sends a message to actor B. Actor B wants to send a message back - but for actor B to send messages to actor A, it needs to know actor A's concrete type *or* that it implements a trait. Now if actor C calls B, it either has to impl the same trait, or B needs to know how to talk to A and C.

If A and C provide B with a closure, where the closure is something like:

for A:
```
    redis_actor.get("key", |cache_response| {
        self.handle_response(cache_response)
    })
```

for C:
```
    redis_actor.get("key", |cache_response| {
        self.use_res(cache_response)
    })
```

Notice that A and C use different methods to handle responses, which is why the redis actor cant just send the message back.

So the return value of the redis cache, in 'route_msg', can be a closure encapsulating the return value. Its sole purpose is to send the message to another actor - a nice thing here is that if actor A or C knows the name of another actor, the closure can route the message directly to that other actor, avoiding having to go through A or C to get to its destination.

Ideally, anyone using this crate should never be exposed to futures. If they want to use futures, they have access to a handle and can totally do so, but since actors don't really return data directly, you'd end up with .wait() everywhere I think.

That said, I like your idea too. I wonder if it's worth supporting both forms of receiving a value back from an actor - I believe Pykka/ Akka support what you've implemented here, so it's fair to say that someone else would find value.

It may make sense to have a separate API that returns futures... not sure. Half of the API returns futures, the other half of the API takes closures for return values. Unfortunately, no function overloading in rust, so one API would have to be something like method_name_future (for a future based method derived from a synchronous method_name).

Anyways, what do you think?

**Comment by mrobakowski** [comment]
Oh right, I think I might have my mind corrupted by writing too much javascript at work. I was thinking that you could just write something like this in futures-rs:
```rust
impl MyActor {
    fn foo(&self, self_actor: &MyActorActor /* we would have to add support for self actor reference as well */) {
        let future_result = bar_actor.do_something(baz);
        // ** the important part **
        future_result.then(|result| {
            self_actor.do_sth_with_result(result);
            future::ok(())
        });
        // do something here without waiting for results 
    }
    fn do_sth_with_result(res: Qux) { ... }
}
```
... but that wouldn't work, would it? Applying `.then(...)` on a rust future doesn't actually send the closure to be executed after the future is complete, does it? If it did, just like it does in JS, then there wouldn't be any benefit to the solution you propose.

We could pass the executor handle to the method as well, if it requests it, and then the user would just pass their future to that for execution... but that sounds far less ergonomic than the callback solution (we would need self-actor reference in the callback version as well, I think).

I recon adding the suppport for both solutions wouldn't be too bad, as I can imagine situations where you would want to mix your actors with futures-rs code. We could either generate both variants of the method always (one with a suffixed name), or make it configurable somehow:

```rust
#[derive_actor(handle_result = future)] // setting the default
impl Foo {
    fn foo() -> i32 { 0 } // produces impl Future<Item = i32>, as the default suggests
    #[handle_result(callback)]
    fn bar() -> f64 { 1.0f64 } // adds a closure to the argument list
    #[handle_result(future)]
    fn quux() -> Option<String> { Some("quux".into()) } // also Future, explicitely
    #[handle_result(both)]
    fn quux2() -> Option<String> { Some("quux2".into()) } // two methods generated, one with suffixed name
}
```

That's how I see it. Again, I am pretty new to futures-rs and I didn't test if `.then` somehow schedules execution or not. If it does, then I would be for doing it futures-only (but `.then` doing that feels somehow not rusty and not-zero-cost, so I doubt it).

**Comment by insanitybit** [comment]
Oh, I really like the annotation idea, that's *much* cleaner than duplicating the API.

Yes, for the closure version to work I intend to add a field to the underlying structure (Foo) that contains a reference to the actor. I also expect most structs that use this macro to already take a Handle, as it's necessary in order to spawn child actors - the macro could also just provide it (since we can manipulate the struct).

As you said in your example, your future wouldn't actually execute without a .wait(), at which point I think we're losing the benefits. I do see what you mean though where the future captures the self reference, that's pretty cool.

The other side of this is that the underlying struct could just return futures in its API. Then the closure would receive a future as its argument, and you could do whatever you want with it. I wonder if, given this, it's worth supporting at the actor level. If you want to get a future back, just return one from the underlying API, right?

edit: Fundamentally though, I think the benefit of a future API is twofold - futures are where the rust ecosystem lies, so we gain familiarity and interop. But regarding the actors framework, I'd rather futures be something you have to opt into. In my mind, the closure is a necessary solution - it allows you to think 'in actors', not in futures and actors. so the question is how the future-based API fits into it. Actors should only ever really be communicating via message passing, I do worry that a futures API would encourage weird patterns.

**Comment by insanitybit** [comment]
Upon further thought, I think the way to go is to get the closure working, see if a separate Future-version is necessary at that point, and go from there.

**Comment by mrobakowski** [comment]
I guess you're right. If we have closures handling results, the users can always futures::sync::oneshot thier way to get a future out of that.

**Comment by insanitybit** [comment]
That's what I'm thinking. I'm going to try to implement the self-actor reference sometime in the next week, at which point the library is going to be stable enough to build something off of. That should give some good ergonomic feedback on whether a promise API is necessary.

**Comment by insanitybit** [comment]
I think I can take the code you've written here and adapt it to use a closure-based system.

**Pull request closed without merging**
